### ISSUE TITLE
Docker-compose.yaml file ?

### ISSUE THREAD

**Issue by championc** [3cky/mbusd#102]
Can I make the installation using a docker-compose.yaml ?

Can you share a sample ?

**Comment by jpmeijers** [comment]
```
services:
  mbusd:
    restart: unless-stopped
    privileged: true
    build:
      context: https://github.com/jpmeijers/mbusd.git
      dockerfile: Dockerfile
    volumes:
      - /dev:/dev
      - ./mbusd.conf:/etc/mbusd.conf
    ports:
      - 502:502
```
