### ISSUE TITLE
usr/bin/mbusd: line 1: syntax error: unexpected "(" when running docker

### ISSUE THREAD

**Issue by rjulius23** [3cky/mbusd#105]
Hi,

I am running the docker container with the following config:

```
    mbusd:
      init: true
      image: 3cky/mbusd:latest
      container_name: mbusd
      volumes:
        - ./mbusd.conf:/etc/mbusd.conf
      restart: always
      privileged: true
#      # To expose devices such as Z-wave receiver.. etc
      devices:
        - /dev/ttyUSB0:/dev/ttyUSB0
      ports:
        - "8091:502"
      restart: always
      labels:
        - "com.yabune.home.component=core"
 ```

It gives the following error:

mbusd is up-to-date
Attaching to mbusd
mbusd                    | /usr/bin/mbusd: line 1: syntax error: unexpected "("

Any ideas ?

It is running on a Raspberry 4 with SSD
